"""
monitoring/metrics.py

Prometheus metric definitions and GPU background poller.
Import this module once at startup; all metrics are module-level singletons.
"""
import threading
import time

from prometheus_client import Counter, Gauge, Histogram

# ---------------------------------------------------------------------------
# Request-level metrics
# ---------------------------------------------------------------------------

REQUEST_COUNT = Counter(
    "agent_requests_total",
    "Total /ask requests",
    ["status"],  # "ok" | "error"
)

REQUEST_LATENCY = Histogram(
    "agent_request_latency_seconds",
    "End-to-end /ask latency",
    buckets=[0.5, 1, 2, 5, 8, 10, 15, 20, 30],
)

# ---------------------------------------------------------------------------
# Per-node pipeline metrics
# ---------------------------------------------------------------------------

NODE_LATENCY = Histogram(
    "agent_node_latency_seconds",
    "Wall-clock time spent inside each LangGraph node",
    ["node"],
    buckets=[0.05, 0.1, 0.5, 1, 2, 5, 10],
)

# ---------------------------------------------------------------------------
# Token metrics  (local model — counted from tokenizer, not billed)
# ---------------------------------------------------------------------------

INPUT_TOKENS = Counter(
    "agent_input_tokens_total",
    "Cumulative prompt tokens fed to the model",
)

OUTPUT_TOKENS = Counter(
    "agent_output_tokens_total",
    "Cumulative tokens generated by the model",
)

# ---------------------------------------------------------------------------
# Agent behaviour metrics
# ---------------------------------------------------------------------------

VERIFY_FAILURES = Counter(
    "agent_verify_failures_total",
    "Number of times the verify node returned verified=False",
)

FALLBACK_COUNT = Counter(
    "agent_fallback_total",
    "Fallback retrieval triggers",
    ["type"],  # "local" | "web"
)

QUESTION_TYPE = Counter(
    "agent_question_type_total",
    "Questions processed by type",
    ["qtype"],  # "bridge" | "comparison"
)

# ---------------------------------------------------------------------------
# GPU metrics  (polled every N seconds by a background thread)
# ---------------------------------------------------------------------------

GPU_MEMORY_USED_BYTES = Gauge(
    "gpu_memory_used_bytes",
    "VRAM currently in use",
    ["gpu_id"],
)

GPU_MEMORY_TOTAL_BYTES = Gauge(
    "gpu_memory_total_bytes",
    "Total available VRAM",
    ["gpu_id"],
)

GPU_UTILIZATION_PERCENT = Gauge(
    "gpu_utilization_percent",
    "GPU compute utilisation (0-100)",
    ["gpu_id"],
)

GPU_TEMPERATURE_CELSIUS = Gauge(
    "gpu_temperature_celsius",
    "GPU die temperature in °C",
    ["gpu_id"],
)


# ---------------------------------------------------------------------------
# GPU background poller
# ---------------------------------------------------------------------------

def _gpu_poll_loop(interval: float) -> None:
    try:
        import pynvml  # nvidia-ml-py
        pynvml.nvmlInit()
    except Exception as exc:
        print(f"[metrics] GPU monitoring unavailable: {exc}")
        return

    while True:
        try:
            count = pynvml.nvmlDeviceGetCount()
            for i in range(count):
                handle = pynvml.nvmlDeviceGetHandleByIndex(i)
                mem  = pynvml.nvmlDeviceGetMemoryInfo(handle)
                util = pynvml.nvmlDeviceGetUtilizationRates(handle)
                temp = pynvml.nvmlDeviceGetTemperature(
                    handle, pynvml.NVML_TEMPERATURE_GPU
                )
                gid = str(i)
                GPU_MEMORY_USED_BYTES.labels(gpu_id=gid).set(mem.used)
                GPU_MEMORY_TOTAL_BYTES.labels(gpu_id=gid).set(mem.total)
                GPU_UTILIZATION_PERCENT.labels(gpu_id=gid).set(util.gpu)
                GPU_TEMPERATURE_CELSIUS.labels(gpu_id=gid).set(temp)
        except Exception:
            pass
        time.sleep(interval)


def start_gpu_collector(interval: float = 5.0) -> None:
    """Launch a daemon thread that updates GPU gauges every `interval` seconds."""
    t = threading.Thread(
        target=_gpu_poll_loop, args=(interval,), daemon=True, name="gpu-metrics"
    )
    t.start()
